# This file defines the content types on the website. See the documentation for
# details: https://docs.bolt.cm/contenttypes/intro

# The Homepage content type is a singleton: There can be only one record of this
# content type.

homepage:
    name: Homepage
    singular_name: Homepage
    fields:
        title:
            type: text
            class: large
            group: content
            label: Title
            allow_html: true
        teaser:
            type: html
            height: 150px
        carousel:
            type: imagelist
            group: Carousel
        features_title:
            type: text
            group: Features
        features:
            type: collection
            fields:
                feature:
                    type: set
                    fields:
                        name:
                            type: text
                            variant: inline
                        image:
                            type: image
                            variant: inline
                        description:
                            type: redactor
        slug:
            type: slug
            uses: title
            group: meta
    singleton: true
    default_status: published
    icon_many: "fa:home"
    icon_one: "fa:home"


# Pages can be used for the more 'static' pages on your site. This content-type
# has a 'templateselect' field, which allows you to override the record_template
# setting for an individual page.
# The taxonomy for this ContentType is defined as 'groups', which is a so-called
# "grouping taxonomy". This way you can easily group sets of pages that logically
# belong together. If your site has a 'services' section, in which you'd like to
# list the different types of services a company provides, you can group these
# together.

pages:
    name: Pages
    singular_name: Page
    fields:
        title:
            type: text
            class: large
            group: content
        subtitle:
            type: text
        slug:
            type: slug
            uses: title
        image:
            type: image
        content:
            type: article
        template:
            type: templateselect
            filter: '*.twig'
            default: 'page.twig'
    records_per_page: 50
    record_route: content_seo

news:
    name: News
    singular_name: Newsitem
    records_per_page: 50
    fields:
        title:
            type: text
            class: large
            allow_html: true
        image:
            type: image
        content:
            type: redactor
        slug:
            type: slug
            uses: title
    icon_many: "fa:newspaper"
    icon_one: "fa:newspaper"


# The 'Blocks' ContentType is a so-called 'resource ContentType'. This means
# that it can be used to manage smaller pieces of content, like the 'about us'
# text, an 'our address' in the footer, or similar short blurbs of text.
# For more info, see: https://docs.bolt.cm/howto/resource-contenttype

features:
    name: Features
    title_format: "{order} - {title}"
    singular_name: Feature
    fields:
        title:
            type: text
            class: large
        slug:
            type: slug
            uses: title
        image:
            type: image
        content:
            type: redactor
        highlight:
            type: select
            values: [ developers, designers, 'content-editors']
            multiple: true
        order:
            type: number
            variant: inline
    taxonomy: [ audience ]
    icon_many: "fa:bug"
    icon_one: "fa:bug"
    viewless: true
    sort: order
    records_per_page: 50

blocks:
    name: Blocks
    singular_name: Block
    fields:
        title:
            type: text
            class: large
            group: "Block"
            label: De Titel
        order:
            type: number
        slug:
            type: slug
            uses: [ title ]
        content:
            type: markdown
            sanitise: false
        #        contentlink:
        #            type: text
        #            label: Link
        #            placeholder: 'contenttype/slug or http://example.org/'
        #            postfix: "Use this to add a link for this Block. This could either be an 'internal' link like <tt>page/about</tt>, if you use a contentType/slug combination. Otherwise use a proper URL, like `http://example.org`."
        image:
            type: image
            attrib: title
            extensions: [ gif, jpg, png ]
        variant:
            type: select
            values:
                'default': "Default"
                'image-left': "Image left"
                'image-right': "Image right"
                'install': "Installation"
                'screenshots': "Screenshots"
                'logopanels': "Logo panels"
    show_on_dashboard: true
    viewless: true
    sort: order
    default_status: published
    searchable: false
    icon_many: "fa:cubes"
    icon_one: "fa:cube"
    records_per_page: 100

blockquotes:
    name: Blockquotes
    singular_name: Blockquote
    fields:
        slug:
            type: slug
            uses: quote
        quote:
            type: textarea
        url:
            type: text
            postfix: The blockquote will be used on a page that matches this canonical url. For example, / for homepage and /newsitem/one-two-three for a news.
        person:
            type: set
            fields:
                photo:
                    type: image
                    variant: inline
                fullname:
                    type: text
                    variant: inline
                position:
                    type: text
                    variant: inline
    icon_many: "fa:quote-left"
    icon_one: "fa:quote-left"
    viewless: true

showcases:
    name: Showcases
    singular_name: Showcase
    fields:
        title:
            type: text
            class: large
        slug:
            type: slug
            uses: title
        website_name:
            type: text
        website_link:
            type: text
            label: Link
            placeholder: 'http://example.org/'
        screenshot:
            type: image
        publication_date:
            type: date
            mode: datetime
        contributor:
            type: redactor
        order:
            type: number
    listing_records: 100
    sort: order

# Possible field types:
#
# text - varchar(256) - input type text.
# integer - integer - Input field for integer numbers.
# float - double - Input field for floating numbers, stored as 'Double'.
# geolocation - text (65kb) - Input field for geolocation. Enter an address, and the location is geocoded to latitude/longitude coordinates
# imagelist - text (65kb) - Input type for imagelists. Add multiple images with a description. Useful for image sliders, galleries, etcetera.
# image - varchar(256) - image select/upload widget, stored as filename.
# file - varchar(256) - file select/upload widget, stored as filename.
# filelist - text (65kb) - Input type for a list of files. Including a description.
# video - varchar(256) - Video embed widget, stored as filename.
# html - text (65kb) - wysiwyg element.
# textarea - varchar(32768) - Simple, plain < textarea > field.
# markdown - varchar(32768) - Simple, plain < textarea > field, which is parsed as Markdown text.
# datetime - datetime - date and time selector widget.
# date - datetime - date selector widget.
# select - varchar(256) - select with predefined values
# templateselect - varchar(256) - select with template filenames
# checkbox - integer - checkbox-field which is 1 (checked) or 0 (unchecked)

# Using YAML repeated nodes
#
# YAML allows the defining of "repeated nodes". These allow you to define a 'node'
# with a 'key: &name' and referenced later with '<<: *name'
#
# Bolt allows you to define this with the special entry of '__nodes:' that itself
# won't create a ContentType, but will allow you to use it in actual ContentTypes
# to prevent repeating yourself.
#
# To achieve this, first create a key '__nodes:'
#__nodes:
#    field_defaults: &field_defaults
#        title:
#            type: text
#            class: large
#            group: main
#        slug:
#            type: slug
#            uses: title
#    template_defaults: &template_defaults
#        template:
#            type: templateselect
#            filter: '*.twig'
#            group: meta
#
# Then, as an example, you could create a ContentType with default fields, with
# an additional 'image' field.
#
#contenttype_abc:
#    name: ContentType Abc
#    fields:
#        <<: *field_defaults
#        image:
#            type: image
#            attrib: title
#            extensions: [ gif, jpg, png ]
#        <<: *template_defaults
#    taxonomy: [ chapters ]
#    recordsperpage: 10
#
# Alternatively, or additionally, you then can then create a ContentType with
# default fields, and a 'select' field, and a different 'templateselect' option.
#
#contenttype_xyz:
#    name: ContentType Xyz
#    fields:
#        <<: *field_defaults
#        selectfield:
#            type: select
#            values: [ none, foo, bar ]
#        template:
#            type: templateselect
#            filter: '*_xyz.twig'
#    taxonomy: [ tags ]
#    recordsperpage: 20
