# This file defines the menus on the website. See the documentation for
# details: https://docs.bolt.cm/configuration/menus

main:
  - label: Features
    link: /features
    submenu:
      - label: For developers
        link: /features-developers
      - label: For designers
        link: /features-designers
      - label: For editors
        link: /features-editors
  - label: Documentation
    link: https://docs.bolt.cm
  - label: Community
    link: /community
#  - label: Contribute
#    link: contribute
#  - label: Extensions
#    link: /extensions
  - label: No costs
    link: /no-costs
  - label: News
    link: /news
  - label: Try it!
    link: https://docs.bolt.cm/installation/installation
    class: site-header__end

footer:
  - label: AboutBoltcms
    submenu:
      - label: News
        link: /news
      - label: Donwload latest version
        link: https://github.com/bolt/core/releases/latest
  - label: Features
    submenu:
      - label: For everyone
        link: /features
      - label: For developers
        link: /features-developers
      - label: For designers
        link: /features-designers
      - label: For editors
        link: /features-editors
  - label: Resources
    submenu:
      - label: Documentation
        link: https://docs.bolt.cm
      - label: Best practice tips
        link: https://bolt.tips
  - label: Community & Contribute
    submenu:
      - label: Community
        link: /community
      - label: Contribute
        link: /contribute
  - label: Explore more
    submenu:
      - label: Extensions
        link: /extensions
      - label: No costs
        link: /no-costs
      - label: News
        link: /news
      - label: Try it!
        link: https://docs.bolt.cm/installation/installation
#  - label: Bolt 3 site
#    link: https://bolt.cm
#    class: bolt-site
#    title: Visit the excellent Bolt website!

