# This file defines the menus on the website. See the documentation for
# details: https://docs.bolt.cm/configuration/menus

main:
  - label: Documentation
    link: https://docs.bolt.cm/4.0
  - label: Community [Slack]
    link: https://bolt.cm/community
  - label: Code on Github
    link: https://github.com/bolt
  - label: News
    link: /news
#  - label: Bolt 3 site
#    link: https://bolt.cm
#    class: bolt-site
#    title: Visit the excellent Bolt website!

