# This file defines the menus on the website. See the documentation for
# details: https://docs.bolt.cm/configuration/menus

main:
  - label: Features
    link: /features
  - label: Documentation
    link: https://docs.bolt.cm
  - label: Extensions
    link: https://extensions.boltcms.io
  - label: News
    link: /news
  - label: Get started now
    link: /
    class: btn btn-primary
#  - label: Bolt 3 site
#    link: https://bolt.cm
#    class: bolt-site
#    title: Visit the excellent Bolt website!

